# Generated by Django 4.2.6 on 2023-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('toys', 'Toys'), ('home_appliances', 'Home Appliances'), ('other_category', 'Other')], default='other_category', max_length=20),
        ),
    ]
