# Generated by Django 4.2.6 on 2023-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Store', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('toys', 'Toys'), ('home_appliances', 'Home Appliances'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
