# Generated by Django 4.2.6 on 2023-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Store', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Toys', 'Toys'), ('Home_appliances', 'Home Appliances'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
