# Generated by Django 3.2.23 on 2023-12-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Store', '0005_alter_cartitem_product_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default_image.png', upload_to='product_images'),
        ),
    ]
