# Generated by Django 3.2.23 on 2023-12-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_Store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_Store.customuser'),
            preserve_default=False,
        ),
    ]
