# Generated by Django 3.2.23 on 2023-12-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_Store', '0009_auto_20231205_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_Store.customuser'),
            preserve_default=False,
        ),
    ]
